name: basictest

on:
  push:
  pull_request:
  schedule:
    - cron: '30 11 * * 2'  # 11:30 every Tuesday

jobs:
  run_all_notebooks:
    strategy:
      matrix:
        include:
          - { os: ubuntu-latest, python: '3.10' }
          - { os: macos-latest,  python: "3.12" }
    name: ${{ matrix.os }}.python-${{ matrix.python }}
    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        path: src

    - name: Setup python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python }}

#    - name: Pip install
#      run: python3 -m pip install ncrystal[all]>=4.0.0

    - name: Check versions
      shell: bash
      run: |
        set -eux
        which python3
        python3 --version
        which cmake
        cmake --version
        nctool --version
        ncrystal-config -s

    - name: Launch tests
      shell: bash
      run: |
        set -eux
        ./src/.github/resources/run_notebooks.x
